//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"

class Jamnik : public Pies {
public:
	int x;
	int y;
	void Operation1();
};

#endif  //_JAMNIK_H
