//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"

class Pies : public Ssak {
public:
	int x;
	int y;
	void Operation1();
};

#endif  //_PIES_H
