//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H

#include "Zwierze.h"

class Ssak : public Zwierze {
public:
	int x;
	int y;
	void Operation1();
};

#endif  //_SSAK_H
