//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#include "Ssak.h"

void Ssak::Operation1() {

}

