//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zwierze.cpp
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#include "Zwierze.h"

void Zwierze::Operation1() {

}

