//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#include "TUniversity.h"

void TUniversity::printData() {

}

void TUniversity::setdata(string name, int age) {

}

TUniversity::TUniversity(string univName) {

}

