//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBook.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_TBOOK_H)
#define _TBOOK_H


class TBook {
public:
	string bookTitle;
	string shelfMark;
	TBook();
	~TBook();
	void setTitle(string title);
	string getTitle();
	void setShelfMark(string mark);
	string getShelfMark();
};

#endif  //_TBOOK_H
